[[constraint]]
  name = "github.com/aws/aws-lambda-go"
  version = "1.x"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.x"

[[constraint]]
  branch = "master"
  name = "golang.org/x/oauth2"

[[constraint]]
  name = "github.com/ashwanthkumar/slack-go-webhook"
  version = "0.3.0"
