name: Build

on:
  push:
    branches-ignore:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-go@v1.0.0
    - run: ./.github/workflows/setup.sh
    - run: ./.github/workflows/build.sh
