name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-go@v1.0.0
    - run: ./.github/workflows/setup.sh
    - run: ./.github/workflows/build.sh
    - uses: actions/setup-node@v1.1.0
    - run: npm i -g serverless
    - run: sls deploy --verbose
      env:
        AKERUN_CLIENT_ID: ${{ secrets.AKERUN_CLIENT_ID }}
        AKERUN_CLIENT_SECRET: ${{ secrets.AKERUN_CLIENT_SECRET }}
        AKERUN_REDIRECT_URL: ${{ secrets.AKERUN_REDIRECT_URL }}
        S3_BUCKET: ${{ secrets.S3_BUCKET }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

